const {chromium}=require('playwright'),fs=require('fs');
const previous=JSON.parse(fs.readFileSync('experiments/winner.json'));const candidates=[previous];
for(const replan of [4,8,16])for(const dodge of [60,180,300])for(const evade of [false,true])candidates.push({...previous,id:'r'+replan+'-d'+dodge+'-e'+evade,replan,dodge,evade});
const metric=r=>{const scores=r.map(x=>x.score).sort((a,b)=>a-b);return r.reduce((a,x)=>a+x.score+Math.max(0,x.stage-1)*800-(!x.eagle?500:0),0)/r.length+scores[Math.floor(scores.length/2)]*.5;};
async function run(page,c,seeds,max=18000){return page.evaluate(({c,seeds,max})=>seeds.map(seed=>{tankAI.start(seed,c);let frames=0,clears=0,previous='start';for(;frames<max;frames++){tankAI.step(1,false);const o=tankAI.observe();if(o.phase==='clear'&&previous!=='clear')clears++;previous=o.phase;if(['gameover','gameover_tally','victory'].includes(o.phase))break;}return {seed,frames,clears,...tankAI.observe()};}),{c,seeds,max});}
(async()=>{fs.mkdirSync('experiments',{recursive:true});const browser=await chromium.launch(require('./tools/browser.cjs'));const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>window.requestAnimationFrame=()=>0);await page.goto('http://127.0.0.1:8787/reference/web/index.html');await page.waitForTimeout(300);
let survivors=candidates,history=[];for(const [round,seeds,keep] of [[1,Array.from({length:8},(_,i)=>i+151),6],[2,Array.from({length:20},(_,i)=>i+159),3],[3,Array.from({length:30},(_,i)=>i+179),1]]){const ranks=[];for(const c of survivors){const runs=await run(page,c,seeds);const record={round,config:c,fitness:metric(runs),mean:runs.reduce((a,x)=>a+x.score,0)/runs.length,clears:runs.reduce((a,x)=>a+x.clears,0),runs};history.push(record);ranks.push(record);console.log(JSON.stringify({round,id:c.id,fitness:record.fitness,mean:record.mean,clears:record.clears}));fs.writeFileSync('experiments/search-refinement.json',JSON.stringify({errors,history},null,2));}ranks.sort((a,b)=>b.fitness-a.fitness);survivors=ranks.slice(0,keep).map(x=>x.config);console.log('SURVIVORS '+JSON.stringify(survivors));}
fs.writeFileSync('experiments/winner-refinement.json',JSON.stringify(survivors[0],null,2));const seeds=Array.from({length:100},(_,i)=>i+2001),validation=[];
for(const c of [previous,survivors[0]]){const runs=await run(page,c,seeds,36000);validation.push({config:c,runs});console.log('HELDOUT '+JSON.stringify({id:c.id,mean:runs.reduce((a,x)=>a+x.score,0)/runs.length,cleared:runs.filter(x=>x.clears>0).length,alive:runs.filter(x=>x.phase==='play'||x.phase==='clear').length,baseDestroyed:runs.filter(x=>!x.eagle).length}));fs.writeFileSync('experiments/heldout-refinement.json',JSON.stringify({errors,validation},null,2));}
await browser.close();})();
