const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch(require('../tools/browser.cjs'));try{
 const meta=JSON.parse(fs.readFileSync(path.join(__dirname,'runs/latest-video.json'))),base=path.join(__dirname,'runs',meta.run),comments=JSON.parse(fs.readFileSync(path.join(base,'danmaku.json'))),processAudit=JSON.parse(fs.readFileSync(path.join(base,'process-audit.json'))),combat=JSON.parse(fs.readFileSync(path.join(base,'combat-audit.json')));
 assert(comments.entries.length>=180);assert.equal(new Set(comments.entries.map(e=>e.text)).size,comments.entries.length);assert.equal(Object.keys(comments.stats.perStage).length,8);assert(comments.stats.maxGapSeconds<=40);
 assert(comments.entries.every(e=>['ai','bilibili','adapted'].includes(e.category)));
 const retained=JSON.parse(fs.readFileSync(path.join(__dirname,'danmaku-ai-retained.json'),'utf8').replace(/^\uFEFF/,''));assert.deepEqual(comments.entries.filter(e=>e.category==='ai').map(e=>({frame:e.frame,text:e.text})),retained.map(e=>({frame:e.frame,text:e.text})));
 const migration=JSON.parse(fs.readFileSync(path.join(__dirname,'danmaku-sources/BV12t411n7wg/migration-report.json'))),originalLines=fs.readFileSync(path.join(__dirname,'danmaku-sources/BV12t411n7wg/original.txt'),'utf8').split(/\r?\n/);
 for(const e of comments.entries.filter(e=>e.category==='bilibili')){assert.equal(e.source.bvid,migration.bvid);assert.equal(e.source.sourceSha256,migration.sourceSha256);assert(originalLines[e.source.line-1].endsWith(e.source.originalText));assert.equal(e.text,e.source.originalText.normalize('NFKC').replace(/[，,]/g,' ').replace(/\s+/g,' ').trim());if(e.source.alignment==='verified_clear_then_ending')assert(e.frame>=combat.frames);}
 const adapted=comments.entries.filter(e=>e.category==='adapted');assert(adapted.length>=60);assert.equal(comments.entries.filter(e=>e.category==='bilibili').length,162);
 for(const e of adapted){assert(e.source.authored);assert.equal(e.source.kind,'adapted_bilibili');assert(originalLines[e.source.parentLine-1].endsWith(e.source.originalText));assert.equal(e.source.parentText,e.source.originalText.normalize('NFKC').replace(/[，,]/g,' ').replace(/\s+/g,' ').trim());assert.notEqual(e.text,e.source.parentText);if(e.source.alignment==='verified_clear_then_ending')assert(e.frame>=combat.frames);}
 const ai=comments.entries.filter(e=>e.category==='ai');assert(ai.length>=40);for(const group of new Set(ai.map(e=>e.replyGroup))){const pair=ai.filter(e=>e.replyGroup===group);assert.equal(pair.length,2);assert.equal(pair[1].frame-pair[0].frame,150);assert(pair.every(e=>e.source.notViewerQuote===true));}
 for(const e of comments.entries){assert(e.text.length<=30);assert.doesNotMatch(e.text,/[，,稳硬]/);const s=e.source;if(['landing','weapon','stage'].includes(s.kind))assert(processAudit.events.some(p=>p.frame===s.frame&&p.kind===s.kind));if(s.kind==='confirmed_gun_kill'||s.kind==='confirmed_sniper_kill')assert(combat.events.some(p=>p.frame===s.frame&&p.kind===(s.kind==='confirmed_gun_kill'?'gun':'sniper')));if(s.kind==='verified_clear')assert(e.frame>=combat.frames);}
 for(let lane=0;lane<3;lane++){const rows=comments.entries.filter(e=>e.lane===lane);for(let i=1;i<rows.length;i++)assert(rows[i].frame>=rows[i-1].frame+rows[i-1].durationFrames);}
 const page=await browser.newPage({viewport:{width:1200,height:1040}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8787/contra/replay.html?v=danmaku&t=844.58');await page.waitForFunction(()=>document.querySelector('video').currentTime>844&&document.querySelectorAll('.danmaku-message').length>=2);await page.evaluate(()=>document.querySelector('video').pause());
 assert.equal(await page.locator('.strategy-card').count(),0);assert.equal(await page.locator('.danmaku-heading').count(),0);assert.equal(await page.locator('#danmaku-quiet').count(),0);
 const before=await page.locator('.danmaku-message').first().evaluate(e=>getComputedStyle(e).transform);await page.waitForTimeout(150);assert.equal(await page.locator('.danmaku-message').first().evaluate(e=>getComputedStyle(e).transform),before);
 await page.screenshot({path:path.join(__dirname,'runs/danmaku-preview-desktop.png'),fullPage:true});
 await page.evaluate(()=>document.querySelector('video').play());await page.waitForTimeout(250);assert.notEqual(await page.locator('.danmaku-message').first().evaluate(e=>getComputedStyle(e).transform),before);await page.evaluate(()=>document.querySelector('video').pause());
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'runs/danmaku-preview-mobile.png'),fullPage:true});
 await page.evaluate(async()=>{const v=document.querySelector('video');await new Promise(resolve=>{v.addEventListener('seeked',resolve,{once:true});v.currentTime=0;});});await page.waitForFunction(()=>document.querySelectorAll('.danmaku-message').length===0);
 const aiStart=ai.find(e=>e.text==='它一命通关 我一命打工');assert(aiStart);await page.setViewportSize({width:1200,height:1040});await page.evaluate(async frame=>{const v=document.querySelector('video');await new Promise(resolve=>{v.addEventListener('seeked',resolve,{once:true});v.currentTime=(frame-2)/60;});},aiStart.frame+330);await page.waitForFunction(()=>[...document.querySelectorAll('.danmaku-message')].some(e=>e.textContent==='它一命通关 我一命打工'));await page.screenshot({path:path.join(__dirname,'runs/danmaku-ai-preview.png'),fullPage:true});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'runs/danmaku-verification.json'),JSON.stringify({passed:true,count:comments.entries.length,uniqueTexts:comments.stats.uniqueTexts,aiComments:ai.length,dialoguePairsVerified:true,sourceEventsVerified:true,noTrackOverlap:true,syncedMovement:true,pauseFreezes:true,seekClears:true,mobileNoOverflow:true,errors},null,2));console.log(`${comments.entries.length} unique comments, ${ai.length} AI comments, paired replies and playback verified.`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
